//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapsLockIndicatorV3 {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CapsLockIndicatorV3.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adjusting color scheme... Please wait....
        /// </summary>
        internal static string adjustingColorScheme {
            get {
                return ResourceManager.GetString("adjustingColorScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Advanced Settings.
        /// </summary>
        internal static string advancedSettings {
            get {
                return ResourceManager.GetString("advancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a I understand the above mentioned risks and wish to proceed.
        /// </summary>
        internal static string advancedSettingsConfirmation {
            get {
                return ResourceManager.GetString("advancedSettingsConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Advanced settings.
        /// </summary>
        internal static string advancedSettingsTitle {
            get {
                return ResourceManager.GetString("advancedSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Changing advanced settings may cause unexpected behaviour and may lead to an unstable state of CapsLock Indicator. Please restart CapsLock Indicator after changing settings. Only change settings if you know what you are doing! Use this editor at your own risk!.
        /// </summary>
        internal static string advancedSettingsWarning {
            get {
                return ResourceManager.GetString("advancedSettingsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Automatically check for updates.
        /// </summary>
        internal static string autoCheckForUpdates {
            get {
                return ResourceManager.GetString("autoCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Background colour activated.
        /// </summary>
        internal static string backgroundColourActivatedButton {
            get {
                return ResourceManager.GetString("backgroundColourActivatedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Background colour deactivated.
        /// </summary>
        internal static string backgroundColourDeactivatedButton {
            get {
                return ResourceManager.GetString("backgroundColourDeactivatedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Border colour activated.
        /// </summary>
        internal static string borderColourActivatedButton {
            get {
                return ResourceManager.GetString("borderColourActivatedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Border colour decativated.
        /// </summary>
        internal static string borderColourDeactivatedButton {
            get {
                return ResourceManager.GetString("borderColourDeactivatedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Border thickness.
        /// </summary>
        internal static string borderThicknessGroup {
            get {
                return ResourceManager.GetString("borderThicknessGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C&amp;ancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Caps lock.
        /// </summary>
        internal static string capsLock {
            get {
                return ResourceManager.GetString("capsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Off.
        /// </summary>
        internal static string cbPersistentCapsOff {
            get {
                return ResourceManager.GetString("cbPersistentCapsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a On.
        /// </summary>
        internal static string cbPersistentCapsOn {
            get {
                return ResourceManager.GetString("cbPersistentCapsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Off.
        /// </summary>
        internal static string cbPersistentNumOff {
            get {
                return ResourceManager.GetString("cbPersistentNumOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a On.
        /// </summary>
        internal static string cbPersistentNumOn {
            get {
                return ResourceManager.GetString("cbPersistentNumOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Off.
        /// </summary>
        internal static string cbPersistentScrollOff {
            get {
                return ResourceManager.GetString("cbPersistentScrollOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a On.
        /// </summary>
        internal static string cbPersistentScrollOn {
            get {
                return ResourceManager.GetString("cbPersistentScrollOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Check for &amp;updates.
        /// </summary>
        internal static string checkForUpdates {
            get {
                return ResourceManager.GetString("checkForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Checking for updates....
        /// </summary>
        internal static string checkingForUpdates {
            get {
                return ResourceManager.GetString("checkingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;Close.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Colours.
        /// </summary>
        internal static string coloursGroup {
            get {
                return ResourceManager.GetString("coloursGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;Exit.
        /// </summary>
        internal static string contextMenuExit {
            get {
                return ResourceManager.GetString("contextMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;Show.
        /// </summary>
        internal static string contextMenuShow {
            get {
                return ResourceManager.GetString("contextMenuShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;Dark mode.
        /// </summary>
        internal static string darkModeOption {
            get {
                return ResourceManager.GetString("darkModeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dismiss.
        /// </summary>
        internal static string dismiss {
            get {
                return ResourceManager.GetString("dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;Dismiss.
        /// </summary>
        internal static string dismissButton {
            get {
                return ResourceManager.GetString("dismissButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Display time.
        /// </summary>
        internal static string displayTime {
            get {
                return ResourceManager.GetString("displayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Download icon packs.
        /// </summary>
        internal static string downloadIcons {
            get {
                return ResourceManager.GetString("downloadIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Download &amp;manually.
        /// </summary>
        internal static string downloadManuallyButton {
            get {
                return ResourceManager.GetString("downloadManuallyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Download more translations....
        /// </summary>
        internal static string downloadMoreTranslations {
            get {
                return ResourceManager.GetString("downloadMoreTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Download translations.
        /// </summary>
        internal static string downloadTranslationsTitle {
            get {
                return ResourceManager.GetString("downloadTranslationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;Exit Application.
        /// </summary>
        internal static string exitApplication {
            get {
                return ResourceManager.GetString("exitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exiting the application means the icons and notifications are no longer displayed. Exit anyway?.
        /// </summary>
        internal static string exitMessage {
            get {
                return ResourceManager.GetString("exitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Failed to download translation.
        /// </summary>
        internal static string failedToDownloadTranslationToolTip {
            get {
                return ResourceManager.GetString("failedToDownloadTranslationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Allow CapsLock Indicator to periodically check for updates online (can be changed later).
        /// </summary>
        internal static string firstRunAllowUpdateCheck {
            get {
                return ResourceManager.GetString("firstRunAllowUpdateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;Dark.
        /// </summary>
        internal static string firstRunColorSchemeDark {
            get {
                return ResourceManager.GetString("firstRunColorSchemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a L&amp;ight.
        /// </summary>
        internal static string firstRunColorSchemeLight {
            get {
                return ResourceManager.GetString("firstRunColorSchemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Which color scheme do you prefer?.
        /// </summary>
        internal static string firstRunColorSchemePreference {
            get {
                return ResourceManager.GetString("firstRunColorSchemePreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Only available on Windows 10 or later.
        /// </summary>
        internal static string firstRunColorSchemeWin10Only {
            get {
                return ResourceManager.GetString("firstRunColorSchemeWin10Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contribute.
        /// </summary>
        internal static string firstRunContribute {
            get {
                return ResourceManager.GetString("firstRunContribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;Exit.
        /// </summary>
        internal static string firstRunExit {
            get {
                return ResourceManager.GetString("firstRunExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Welcome to CapsLock Indicator.
        /// </summary>
        internal static string firstRunHeading {
            get {
                return ResourceManager.GetString("firstRunHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Thank you for choosing CapsLock Indicator! This program is open-source and free, always has been, always will be! Are you interested in contributing to CapsLock Indicator yourself? Visit the link below for more information! Also, please take a moment to review the settings below!.
        /// </summary>
        internal static string firstRunMessage {
            get {
                return ResourceManager.GetString("firstRunMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a What information will be sent?.
        /// </summary>
        internal static string firstRunPrivacyInfoLinkLabel {
            get {
                return ResourceManager.GetString("firstRunPrivacyInfoLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;Let&apos;s go!.
        /// </summary>
        internal static string firstRunStart {
            get {
                return ResourceManager.GetString("firstRunStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Font.
        /// </summary>
        internal static string fontGroup {
            get {
                return ResourceManager.GetString("fontGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Text colour activated.
        /// </summary>
        internal static string foregroundColourActivatedButton {
            get {
                return ResourceManager.GetString("foregroundColourActivatedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Text colour deactivated.
        /// </summary>
        internal static string foregroundColourDeactivatedButton {
            get {
                return ResourceManager.GetString("foregroundColourDeactivatedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a You can show CapsLock Indicator again by double clicking on this icon..
        /// </summary>
        internal static string generalIconBalloonText {
            get {
                return ResourceManager.GetString("generalIconBalloonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Warning!.
        /// </summary>
        internal static string headerWarning {
            get {
                return ResourceManager.GetString("headerWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hide on start up.
        /// </summary>
        internal static string hideOnStartup {
            get {
                return ResourceManager.GetString("hideOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;Hide window.
        /// </summary>
        internal static string hideWindow {
            get {
                return ResourceManager.GetString("hideWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Downloading metadata....
        /// </summary>
        internal static string iconPackDownloadingMetadata {
            get {
                return ResourceManager.GetString("iconPackDownloadingMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Downloading pack....
        /// </summary>
        internal static string iconPackDownloadingPack {
            get {
                return ResourceManager.GetString("iconPackDownloadingPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Do you want to install the icon pack “{name}” (Version {version}) by {authorName}?.
        /// </summary>
        internal static string iconPackPrompt {
            get {
                return ResourceManager.GetString("iconPackPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Do you want to reset the icons to the default ones?.
        /// </summary>
        internal static string iconPackResetPrompt {
            get {
                return ResourceManager.GetString("iconPackResetPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Icons were reset to default!.
        /// </summary>
        internal static string iconPackResetSuccess {
            get {
                return ResourceManager.GetString("iconPackResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Successfully installed icon pack “{name}” (Version {version})!.
        /// </summary>
        internal static string iconPackSuccess {
            get {
                return ResourceManager.GetString("iconPackSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} changed.
        /// </summary>
        internal static string keyChanged {
            get {
                return ResourceManager.GetString("keyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} is off.
        /// </summary>
        internal static string keyIsOff {
            get {
                return ResourceManager.GetString("keyIsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} is on.
        /// </summary>
        internal static string keyIsOn {
            get {
                return ResourceManager.GetString("keyIsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;Notification settings.
        /// </summary>
        internal static string notificationSettings {
            get {
                return ResourceManager.GetString("notificationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Notification Settings.
        /// </summary>
        internal static string notificationSettingsTitle {
            get {
                return ResourceManager.GetString("notificationSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Num lock.
        /// </summary>
        internal static string numLock {
            get {
                return ResourceManager.GetString("numLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;OK.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Opacity.
        /// </summary>
        internal static string opacity {
            get {
                return ResourceManager.GetString("opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Overlay position.
        /// </summary>
        internal static string overlayPositionGroup {
            get {
                return ResourceManager.GetString("overlayPositionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Permanently.
        /// </summary>
        internal static string permanentIndicator {
            get {
                return ResourceManager.GetString("permanentIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ...Caps lock is.
        /// </summary>
        internal static string persistentCapsLabel {
            get {
                return ResourceManager.GetString("persistentCapsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Show persistent overlay when....
        /// </summary>
        internal static string persistentHeadingLabel {
            get {
                return ResourceManager.GetString("persistentHeadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ...Num lock is.
        /// </summary>
        internal static string persistentNumLabel {
            get {
                return ResourceManager.GetString("persistentNumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ...Scroll lock is.
        /// </summary>
        internal static string persistentScrollLabel {
            get {
                return ResourceManager.GetString("persistentScrollLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Reloaded icons.
        /// </summary>
        internal static string reloadedIconsInfo {
            get {
                return ResourceManager.GetString("reloadedIconsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Reset settings.
        /// </summary>
        internal static string resetSettings {
            get {
                return ResourceManager.GetString("resetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This will reset all settings to their default values and restart CapsLock Indicator. All customisation will be lost! This cannot be undone!
        ///Do you want to reset all settings now?.
        /// </summary>
        internal static string resetSettingsConfirmationText {
            get {
                return ResourceManager.GetString("resetSettingsConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;Restart.
        /// </summary>
        internal static string restart {
            get {
                return ResourceManager.GetString("restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Restart application.
        /// </summary>
        internal static string restartApplication {
            get {
                return ResourceManager.GetString("restartApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;Save &amp;&amp; close.
        /// </summary>
        internal static string saveAndCloseButton {
            get {
                return ResourceManager.GetString("saveAndCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Scroll lock.
        /// </summary>
        internal static string scrollLock {
            get {
                return ResourceManager.GetString("scrollLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Search for &amp;updates on resume.
        /// </summary>
        internal static string searchForUpdatesOnResumeOption {
            get {
                return ResourceManager.GetString("searchForUpdatesOnResumeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The settings have moved! You will now find them in these tabs up here!.
        /// </summary>
        internal static string settingsChangedToolTip {
            get {
                return ResourceManager.GetString("settingsChangedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Show icons for....
        /// </summary>
        internal static string showIconsFor {
            get {
                return ResourceManager.GetString("showIconsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Show no icons.
        /// </summary>
        internal static string showNoIcons {
            get {
                return ResourceManager.GetString("showNoIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Show no notification.
        /// </summary>
        internal static string showNoNotification {
            get {
                return ResourceManager.GetString("showNoNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Show notification when....
        /// </summary>
        internal static string showNotificationWhen {
            get {
                return ResourceManager.GetString("showNotificationWhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Always show overlay when active.
        /// </summary>
        internal static string showOverlayOnlyWhenActive {
            get {
                return ResourceManager.GetString("showOverlayOnlyWhenActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Start on logon.
        /// </summary>
        internal static string startOnLogon {
            get {
                return ResourceManager.GetString("startOnLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Advanced Options.
        /// </summary>
        internal static string tabAdvancedOptions {
            get {
                return ResourceManager.GetString("tabAdvancedOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a General.
        /// </summary>
        internal static string tabGeneral {
            get {
                return ResourceManager.GetString("tabGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Notification.
        /// </summary>
        internal static string tabNotification {
            get {
                return ResourceManager.GetString("tabNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This version of CapsLock Indicator (Version {version}) is not supported. Please update to the latest version!.
        /// </summary>
        internal static string unsupportedCLI {
            get {
                return ResourceManager.GetString("unsupportedCLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a You are using {os} which is no longer supported by Microsoft. CapsLock Indicator will drop support for this OS in the future! Please upgrade to a modern version of Windows!.
        /// </summary>
        internal static string unsupportedWin {
            get {
                return ResourceManager.GetString("unsupportedWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CapsLock Indicator Update available!.
        /// </summary>
        internal static string updateAvailable {
            get {
                return ResourceManager.GetString("updateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Version {0}, released {1}.
        /// </summary>
        internal static string updateInfoFormat {
            get {
                return ResourceManager.GetString("updateInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Some of the currently installed translations seem to be outdated. Do you want to update them now?.
        /// </summary>
        internal static string updateLocaleMessageBox {
            get {
                return ResourceManager.GetString("updateLocaleMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;Update now.
        /// </summary>
        internal static string updateNow {
            get {
                return ResourceManager.GetString("updateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
